AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  ChannelAccessToken:
    Type: String
    Description: "The access token for the LINE Messaging API"
  BucketName:
    Type: String
    Description: "The name of the S3 bucket where images will be stored"
    Default: ""  # デフォルトは空文字列にして、既存バケットが指定されていない場合は新しく作成
  CreateNewBucket:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "false"  # デフォルトでは新しいバケットは作成しない
  
  Conditions:
  CreateS3Bucket: !Equals [!Ref CreateNewBucket, "true"]  # 新しいバケットを作成するかどうかを判定


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName  # S3バケット名を環境変数に渡す
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName  # S3バケット名を指定

  ImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello_world.image_s3_handler.lambda_handler  # 新しいLambda関数
      Runtime: python3.8
      Environment:
        Variables:
          CHANNEL_ACCESS_TOKEN: !Ref ChannelAccessToken
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName  # S3バケット名を指定
      Events:
        LineWebhook:
          Type: Api
          Properties:
            Path: /linewebhook
            Method: post
  
    S3Bucket:
      Type: AWS::S3::Bucket
      Condition: CreateS3Bucket  # このバケットは新しいバケット作成が必要な場合のみ作成される
      Properties:
        BucketName: !Ref BucketName
      DeletionPolicy: Retain  # バケットを削除しない


Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
